import React, { useState } from 'react';
import { Header } from './components/Header';
import { EnvironmentNotice } from './components/EnvironmentNotice';
import { TextInputArea } from './components/TextInputArea';
import { ResultsDashboard } from './components/ResultsDashboard';
import { APP_CONFIG } from './config';
import { DetectorResult } from './types/detector';
import { detectAiText } from './services/detectorService';
import { Sparkles, BookOpen } from 'lucide-react';

export default function App() {
  const [text, setText] = useState<string>('');
  const [selectedOllamaModel, setSelectedOllamaModel] = useState<string>(
    APP_CONFIG.ollama.defaultModel
  );
  const [isLocalPreviewActive, setIsLocalPreviewActive] = useState<boolean>(false);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [result, setResult] = useState<DetectorResult | null>(null);
  const [lastAnalyzedText, setLastAnalyzedText] = useState<string>('');
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const handleAnalyze = async () => {
    if (!text.trim() || text.trim().length < 25) return;

    setIsLoading(true);
    setErrorMessage(null);

    try {
      const data = await detectAiText(text, {
        ollamaModel: selectedOllamaModel,
        useLocalPreviewMode: isLocalPreviewActive,
      });
      setResult(data);
      setLastAnalyzedText(text);
    } catch (err: any) {
      if (err.message === 'MISSING_OPENROUTER_KEY') {
        setIsLocalPreviewActive(true);
        // Fallback to local heuristic preview so user gets immediate results
        try {
          const fallbackData = await detectAiText(text, {
            useLocalPreviewMode: true,
          });
          setResult(fallbackData);
          setLastAnalyzedText(text);
          setErrorMessage(
            'Notice: Live OpenRouter API key not detected in environment. Displaying analysis via the Instant Local Forensic Preview Engine.'
          );
        } catch (innerErr: any) {
          setErrorMessage(innerErr.message || 'Failed to analyze text.');
        }
      } else {
        setErrorMessage(err.message || 'An unexpected error occurred during detection.');
      }
    } finally {
      setIsLoading(false);
    }
  };

  const handleClear = () => {
    setText('');
    setResult(null);
    setErrorMessage(null);
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 flex flex-col font-sans selection:bg-indigo-100 selection:text-indigo-900">
      {/* Top Header */}
      <Header
        selectedOllamaModel={selectedOllamaModel}
        onSelectOllamaModel={setSelectedOllamaModel}
        isLocalPreviewActive={isLocalPreviewActive}
      />

      {/* Main Container */}
      <main className="flex-1 max-w-6xl w-full mx-auto px-4 sm:px-6 py-6 sm:py-8">
        {/* Environment Alert / Notice */}
        <EnvironmentNotice
          isLocalPreviewActive={isLocalPreviewActive}
          onToggleLocalPreview={setIsLocalPreviewActive}
          errorMessage={errorMessage}
        />

        {/* Input Card */}
        <div className="mb-8">
          <TextInputArea
            text={text}
            onChangeText={setText}
            onAnalyze={handleAnalyze}
            isLoading={isLoading}
            onClear={handleClear}
          />
        </div>

        {/* Results Section */}
        {result ? (
          <section aria-label="Detection Results">
            <ResultsDashboard result={result} originalText={lastAnalyzedText || text} />
          </section>
        ) : (
          /* Empty / Explanatory State */
          <div className="bg-white rounded-2xl border border-slate-200 p-6 sm:p-8 text-center max-w-2xl mx-auto shadow-2xs">
            <div className="w-12 h-12 rounded-2xl bg-indigo-50 border border-indigo-100 text-indigo-600 flex items-center justify-center mx-auto mb-4">
              <BookOpen className="w-6 h-6" />
            </div>
            <h3 className="text-base font-bold text-slate-900 mb-1.5">
              Ready to check your text
            </h3>
            <p className="text-xs sm:text-sm text-slate-500 leading-relaxed max-w-md mx-auto mb-6">
              TextSpector checks vocabulary variety, sentence rhythm, and common AI writing habits to see whether writing was composed by a person or generated by AI.
            </p>
            <div className="flex flex-wrap justify-center gap-3">
              <button
                type="button"
                onClick={handleAnalyze}
                disabled={isLoading || text.trim().length < 25}
                className="inline-flex items-center gap-2 px-5 py-2 rounded-xl text-xs sm:text-sm font-semibold bg-slate-900 text-white hover:bg-slate-800 transition-all shadow-xs"
              >
                <Sparkles className="w-4 h-4 text-indigo-400" />
                <span>Check the loaded text</span>
              </button>
            </div>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-200 bg-white py-4 mt-12">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row items-center justify-between text-xs text-slate-400 gap-2">
          <span>TextSpector • AI Text Checker</span>
          <span>OpenRouter & Ollama Ready</span>
        </div>
      </footer>
    </div>
  );
}
